void emp_display_details(char []);
char* add_employee(char [],char [],int,int );
int emp_management(int,int );
char* modify_employee(int);
char* view_pending_requests(char []);
char* add_employee_department(int );
int display_leaves(int);
void view_raised_grievances();
char* update_salary(int);
char* leave_request(int,int,int,int,int,char []);
char* view_pending_leave_requests(char []);
