/** 
 * @file admin_dept_management.c 
 *
 * Perform the Pending request approval and adding employee in the deaprtment by Admin 
 * for fulfiling the requirements of the users.
 *
 */

/* Including basic libraries */
#include<stdio.h>
#include<string.h>
#include<windows.h>
#include<mysql.h>
#include<stdlib.h>

/* Including all dependencies */
#include "..\include\Validation.h"
#include "..\include\employee_management.h"

/* Declaration of connection to MYSQL Database pointers and database port number */
MYSQL *conn5, *conn2;
int port2=3305;

/** 
 * \brief View the pending requests from the users to perform actions from the admin.
 *
 * Admin can access the database and view the requests raised by Manager or Employee 
 * Queries were processed from "employee_request" table and print on the console screen
 * 
 * @param[in] char status[]  status of the reuqest of the user.
 *
 * \return User_Type: Requests displayed successfully: For positive case
 *		   Not connected : Fail to establish the connection with database
 *		   Failed to execute the query: Connection problem for execution of the query
 *
 */

char* view_pending_requests(char status[]){
	MYSQL_RES *read=NULL;
	MYSQL_RES *res=NULL;
	MYSQL_ROW row=NULL;

	char stmt[1500];
	
	/* Selecting the requests generated by the Manager,Employee to perform their actions */
	char qry_req[]={"select * from employee_request where request_status='%s'"};

	/* Creating new connection (conn5) with username and password with the database */
	conn5=mysql_init(NULL);
	mysql_real_connect(conn5, "localhost", "root", "1234","payroll", port2, NULL, 0);

	/* Validating that MYSQL connection (conn5) is established or not */
	if(conn5){
        int n=sprintf(stmt,qry_req,status);
        mysql_query(conn5,stmt);
		read = mysql_store_result(conn5);
        if (mysql_query(conn5,stmt)){
            printf(" Error: %s\n", mysql_error(conn5));
            return ("Failed to execute query.");
        }
		else{
            int i=0;
            int num=0;
            printf("\n");
            printf("REQUEST_ID	  MANAGER_EMP_ID    DEPARTMENT      DESIGNATION	         STATUS");
            printf("\n");
			while((row = mysql_fetch_row(read))){
            	num = mysql_num_fields(read);
            	printf("	");
            	for(i = 0; i < num; i++){
                    printf("%s ", row[i]);
                    printf("	|	");
                }
                printf("\n");
			}
        }
    }
    else{
    	printf("not connected");
        return ("%s", mysql_error(conn5));
	}
	return "\n\n\nRequests displayed successfully";
}

/** 
 * \brief Add the employees in the department when requested by the Manager.
 *
 * Admin can access the database and can add employee in the department requested by Manager 
 * Queries were processed from "employee_request" table and print on the console screen against the unique response ID
 * 
 * @param[in] int request_id Unique request ID for the Employee
 *
 * \return Nothing as all the error messages or positive cases are printing on the console screen
 *
 */

char* add_employee_department(int request_id){
	MYSQL_RES *read=NULL;
	MYSQL_RES *res=NULL;
	MYSQL_ROW row=NULL;
    char dep[20];
    char des[20];
    int check=1;
	char stmt[1500];
	
	/* Query is run to approve the request from manager against each request ID */
	char qry_retrieve[]={"select department,designation from employee_request where request_id='%d'"};
	mysql_real_connect(conn2, "localhost", "root", "1234","payroll", port2, NULL, 0);

	/* Validating that MYSQL connection (conn2) is established or not */
	if(conn2){
		int n=sprintf(stmt,qry_retrieve,request_id);
		mysql_query(conn2,stmt);
		read = mysql_store_result(conn2);
		if (mysql_query(conn2,stmt)){
            printf(" Error: %s\n", mysql_error(conn2));
            printf("Failed to execute query.");
        }
        else{
			row = mysql_fetch_row(read);
			strcpy(dep,row[0]);
			strcpy(des,row[1]);
        }
	}
	
	else{
    	printf("not connected");
        printf("%s\n", mysql_error(conn2));
	}
	/* Calling add_employee function for adding new employee in the department */
	add_employee(dep,des,check,request_id);
}
