/**
* @file admin_dept_management.c
*
* Provides the department functionality to the admin
* Admin can view pending employee requests raised by the manager and take decision accordingly
*
*/

/* Including basic libraries */
#include<stdio.h>
#include<string.h>
#include<windows.h>
#include<mysql.h>
#include<stdlib.h>

/* Including all dependencies */
#include "..\include\validation.h"
#include "..\include\employee_management.h"

/* Declaration of connection to MYSQL Database pointers and database port number */
MYSQL *conn5, *conn2;
int port2=3306;

/**
* \fn char* view_pending_requests(char status[])
* \brief View the pending employee requests raised by the managers to perform actions by the admin.
*
* Admin can access the database and view the employee requests raised by Manager
*
* @param[in] char status[]  status of the pending employee requests
*
* \return string message for request display status
*/

char* view_pending_requests(char status[]){
    MYSQL_RES *read=NULL;
    MYSQL_RES *res=NULL;
    MYSQL_ROW row=NULL;
    char stmt[1500];
    
    /* Selecting the requests generated by the Manager,Employee to perform their actions */
    char qry_req[]={"select * from employee_request where request_status='%s'"};
    
    /* Creating new connection (conn5) with username and password with the database */
    conn5=mysql_init(NULL);
    mysql_real_connect(conn5, "localhost", "root", "1234","payroll", port2, NULL, 0);
    
    /* Validating that MYSQL connection (conn5) is established or not */
    if(conn5){
        int n=sprintf(stmt,qry_req,status);
        mysql_query(conn5,stmt);
        read = mysql_store_result(conn5);
        if (mysql_query(conn5,stmt)){
            printf(" Error: %s\n", mysql_error(conn5));
            return ("Failed to execute query.");
        }else{
            int i=0;
            int num=0;
            printf("\n");
            printf("REQUEST_ID	  MANAGER_EMP_ID    DEPARTMENT      DESIGNATION	         STATUS");
            printf("\n");
            while((row = mysql_fetch_row(read))){
                num = mysql_num_fields(read);
                printf("	");
                for(i = 0; i < num; i++){
                    printf("%s ", row[i]);
                    printf("	|	");
                }
                printf("\n");
            }
        }
    }else{
        printf ("%s\n", mysql_error(conn5));
        return ("not connected");
    }
    return "\n\n\nRequests displayed successfully";
}

/**
*
* \fn char* add_employee_department(int request_id)
* \brief Add the employees by the admin in the department as requested in the employee request by manager
*
* Admin can access the database and can add employee in the department requested by Manager
* The department and designation will correspond to the request that was raised by manager
*
* @param[in] int request_id Unique request ID corresponding to the employee request raised by the manager
*
* \return string message for confirmation
*
*/

char* add_employee_department(int request_id){
    MYSQL_RES *read=NULL;
    MYSQL_RES *res=NULL;
    MYSQL_ROW row=NULL;
    char dep[20];
    char des[20];
    int check=1;
    char stmt[1500];
    
    /* Query is run to approve the request from manager against each request ID */
    char qry_retrieve[]={"select department,designation from employee_request where request_id='%d'"};
    mysql_real_connect(conn2, "localhost", "root", "1234","payroll", port2, NULL, 0);
    
    /* Validating that MYSQL connection (conn2) is established or not */
    if(conn2){
        int n=sprintf(stmt,qry_retrieve,request_id);
        mysql_query(conn2,stmt);
        read = mysql_store_result(conn2);
        if (mysql_query(conn2,stmt)){
            printf(" Error: %s\n", mysql_error(conn2));
            printf("Failed to execute query.");
        }else{
            row = mysql_fetch_row(read);
            strcpy(dep,row[0]);
            strcpy(des,row[1]);
        }
    }else{
        printf("not connected");
        printf("%s\n", mysql_error(conn2));
    }
    /* Calling add_employee function for adding new employee in the department */
    add_employee(dep,des,check,request_id);
}
